(function($) {
    $(document).ready(function() {
	
	$('#flowmap').scianimator({
	    'images': ['images/flowmap1.jpg', 'images/flowmap2.jpg', 'images/flowmap3.jpg', 'images/flowmap4.jpg', 'images/flowmap5.jpg', 'images/flowmap6.jpg', 'images/flowmap7.jpg', 'images/flowmap8.jpg', 'images/flowmap9.jpg', 'images/flowmap10.jpg', 'images/flowmap11.jpg', 'images/flowmap12.jpg', 'images/flowmap13.jpg', 'images/flowmap14.jpg', 'images/flowmap15.jpg', 'images/flowmap16.jpg', 'images/flowmap17.jpg', 'images/flowmap18.jpg', 'images/flowmap19.jpg', 'images/flowmap20.jpg', 'images/flowmap21.jpg', 'images/flowmap22.jpg', 'images/flowmap23.jpg', 'images/flowmap24.jpg', 'images/flowmap25.jpg', 'images/flowmap26.jpg', 'images/flowmap27.jpg', 'images/flowmap28.jpg', 'images/flowmap29.jpg', 'images/flowmap30.jpg', 'images/flowmap31.jpg', 'images/flowmap32.jpg', 'images/flowmap33.jpg', 'images/flowmap34.jpg', 'images/flowmap35.jpg', 'images/flowmap36.jpg', 'images/flowmap37.jpg', 'images/flowmap38.jpg', 'images/flowmap39.jpg', 'images/flowmap40.jpg', 'images/flowmap41.jpg', 'images/flowmap42.jpg', 'images/flowmap43.jpg', 'images/flowmap44.jpg', 'images/flowmap45.jpg', 'images/flowmap46.jpg', 'images/flowmap47.jpg', 'images/flowmap48.jpg', 'images/flowmap49.jpg', 'images/flowmap50.jpg', 'images/flowmap51.jpg', 'images/flowmap52.jpg', 'images/flowmap53.jpg', 'images/flowmap54.jpg', 'images/flowmap55.jpg', 'images/flowmap56.jpg', 'images/flowmap57.jpg', 'images/flowmap58.jpg', 'images/flowmap59.jpg', 'images/flowmap60.jpg', 'images/flowmap61.jpg', 'images/flowmap62.jpg', 'images/flowmap63.jpg', 'images/flowmap64.jpg', 'images/flowmap65.jpg', 'images/flowmap66.jpg', 'images/flowmap67.jpg', 'images/flowmap68.jpg', 'images/flowmap69.jpg', 'images/flowmap70.jpg', 'images/flowmap71.jpg', 'images/flowmap72.jpg', 'images/flowmap73.jpg', 'images/flowmap74.jpg', 'images/flowmap75.jpg', 'images/flowmap76.jpg', 'images/flowmap77.jpg', 'images/flowmap78.jpg', 'images/flowmap79.jpg', 'images/flowmap80.jpg', 'images/flowmap81.jpg', 'images/flowmap82.jpg', 'images/flowmap83.jpg', 'images/flowmap84.jpg', 'images/flowmap85.jpg', 'images/flowmap86.jpg', 'images/flowmap87.jpg', 'images/flowmap88.jpg', 'images/flowmap89.jpg', 'images/flowmap90.jpg', 'images/flowmap91.jpg', 'images/flowmap92.jpg', 'images/flowmap93.jpg', 'images/flowmap94.jpg', 'images/flowmap95.jpg', 'images/flowmap96.jpg'],
	    'width': 640,
	    'delay': 500,
	    'loopMode': 'none',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed'], 'delayMin': 0
	});
    });
})(jQuery);
